name: 'Setup veHub'
description: 'This action sets up the veHub CLI by downloading the latest version.'
author: 'Vector Informatik GmbH'

runs:
    using: composite
    steps:
        - name: Install veHub CLI
          run: sudo ${{ github.action_path }}/setup-vehub.sh
          shell: bash
