name: CI

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup veHub
        uses: ./

      - name: Check installation
        shell: bash
        run: |
          vehub --version
